# -*- coding: utf-8 -*-
"""Cleaning_and _Grouping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMWdHZs2fsk7AXKIvHrMRwAAuJHlFVjb
"""

# This step imports pandas and creates the employee DataFrame.

import pandas as pd

data = {
    "EmployeeID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "Name": ["Sarah", "Michael", "Jennifer", "David", "Lisa",
             "James", "Emma", "Robert", "Sophia", "William"],
    "Department": ["Engineering", "Sales", "Marketing", "Engineering", "HR",
                   "Sales", "Engineering", "Marketing", "Sales", "HR"],
    "Salary": [85000, 62000, 71000, 92000, 58000,
               68000, 78000, 75000, 65000, 60000],
    "Performance Score": [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    "Years of Service": [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}

df = pd.DataFrame(data)

df

# This step selects and displays only specific columns.

df[["Name", "Department", "Salary"]]

# This step uses iloc to display the employee at row index position 5.

df.iloc[5]

# This step uses loc to filter employee with EmployeeID 208.

df.loc[df["EmployeeID"] == 208]

# This step filters employees who belong to the Engineering department.

df[df["Department"] == "Engineering"]

# This step filters employees whose salary is greater than 70000.

df[df["Salary"] > 70000]

# This step filters employees from Sales department with performance score >= 4.

df[(df["Department"] == "Sales") & (df["Performance Score"] >= 4)]

# This step sorts the DataFrame by Salary in descending order and displays top 3 employees.

df.sort_values(by="Salary", ascending=False).head(3)

# This step sorts first by Department (ascending) and then by Salary (descending).

df.sort_values(by=["Department", "Salary"], ascending=[True, False])