# -*- coding: utf-8 -*-
"""EDA_Assignment_Lakshmipavithra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUqnzpc7m_KwrbnfV_sNvXu-ervyonNe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

# Preview data
df.head()

#plt.figure(figsize=(6,4))

plt.hist(df['total_bill'], bins=5, color='skyblue', edgecolor='black')

plt.xlabel("Total Bill (USD)")
plt.ylabel("Frequency")
plt.title("Distribution of Total Bill (5 Bins)")

plt.show()

plt.hist(df['total_bill'], bins=20, color='orange', edgecolor='black')

plt.xlabel("Total Bill (USD)")
plt.ylabel("Frequency")
plt.title("Distribution of Total Bill (20 Bins)")

plt.show()

sns.boxplot(x='day', y='total_bill', data=df)

plt.xlabel("Day")
plt.ylabel("Total Bill (USD)")
plt.title("Total Bill Distribution Across Days")

plt.show()

# Group Sunday data
sun = df[df['day'] == 'Sun']['total_bill']

# Calculate quartiles
Q1 = sun.quantile(0.25)
Q3 = sun.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

import plotly.express as px

fig = px.scatter(
    df,
    x="total_bill",
    y="tip",
    color="time",
    hover_data=["day", "size"],
    title="Relationship Between Total Bill and Tip Amount"
)

fig.show()