# -*- coding: utf-8 -*-
"""Employee_analysis_iitp_aimlt_26011371 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Pv3hZxZjIW4aUGYLS7SiXPw35W00FXa
"""

import sqlite3
import random
import pandas as pd

# Create connection
conn = sqlite3.connect("employees.db")
cursor = conn.cursor()

# Drop table if exists (for re-running safely)
cursor.execute("DROP TABLE IF EXISTS employees")

# Create table
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL,
    years_experience INTEGER,
    performance_score REAL
)
""")

departments = ["Engineering", "Sales", "Marketing", "HR", "Finance"]

# Insert 40 synthetic records
for i in range(1, 41):
    name = f"Employee_{i}"
    department = random.choice(departments)
    salary = random.randint(50000, 150000)
    years_experience = random.randint(1, 15)
    performance_score = round(random.uniform(1.0, 5.0), 2)

    cursor.execute("""
    INSERT INTO employees
    (emp_id, name, department, salary, years_experience, performance_score)
    VALUES (?, ?, ?, ?, ?, ?)
    """, (i, name, department, salary, years_experience, performance_score))

conn.commit()

print("Database and table created successfully")

query1 = """
SELECT name, department, salary, performance_score
FROM employees
WHERE performance_score >= 4.0
AND years_experience >= 3
ORDER BY performance_score DESC
LIMIT 15
"""

query2 = """
SELECT *
FROM employees
WHERE salary BETWEEN 70000 AND 110000
AND department IN ('Engineering', 'Sales')
ORDER BY department ASC, salary DESC
"""

query3 = """
SELECT department,
       COUNT(*) AS employee_count,
       AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC
"""

df_q3 = pd.read_sql_query(query3, conn)
df_q3

df_q2 = pd.read_sql_query(query2, conn)
df_q2

df_q1 = pd.read_sql_query(query1, conn)
df_q1

df_all = pd.read_sql_query("SELECT * FROM employees", conn)

avg_performance = df_all.groupby("department")["performance_score"].mean()
avg_performance

