# -*- coding: utf-8 -*-
"""Pandas_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAyGkja4Ob0E7T-a42RUkXnfpwKpaVMx
"""

import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df.info()
df.isna().sum()

df['region'].fillna(df['region'].mode()[0], inplace=True)
df['product_category'].fillna(df['product_category'].mode()[0], inplace=True)

df['sales_amount'].fillna(df['sales_amount'].median(), inplace=True)

df['quantity'].fillna(method='ffill', inplace=True)
df['customer_age'].fillna(round(df['customer_age'].mean()), inplace=True)

#df.method({'customer_age': fillna(round(df['customer_age'].mean())}, inplace=True)

df.dropna(subset=['payment_method'], inplace=True)


df.isna().sum()

total_sales_region = df.groupby('region')['sales_amount'].sum()
print(total_sales_region)

avg_sales_category = df.groupby('product_category')['sales_amount'].mean()
print(avg_sales_category)

region_product = df.groupby(['region', 'product_category']).agg({
    'sales_amount': 'sum',
    'quantity': 'sum'
}).reset_index()


print(region_product)

top3 = region_product.sort_values(by='sales_amount', ascending=False).head(3)
print(top3)

def sales_range(x):
    return x.max() - x.min()
sales_range_region = df.groupby('region')['sales_amount'].apply(sales_range)
print(sales_range_region)

region_summary = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean', 'max'],
    'quantity': ['sum', 'min']
})

print(region_summary)